spring:
  application:
    name: integration-api
  datasource:
    url: jdbc:postgresql://localhost:5432/integration
    username: user
    password: pass
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
  flyway:
    locations:
      - classpath:/db/migration

# provides nice logging for hibernate with additional information like batch, type, batsh size
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          # uncomment to see more informative logs (batch size, prepared statement etc)
#          listener: debug
          listener: info

server:
  port: 8080
  shutdown: GRACEFUL
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1

# custom batch config
batch-config:
  chunk-size: 10000 # chunk size which determines how many rows are processed during read/process/write

