spring:
  application:
    name: integration-api
  datasource:
    url: jdbc:postgresql://localhost:5432/integration
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  shutdown: GRACEFUL
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1


integration:
  chunk-size: 300
  skip-limit: 100000 # 100k rows


  # todo THINK ABOUT COMPRESSION LOGIC
  # Enable response compression
#  server.compression.enabled=true
#  server.compression.mime-types=application/json,application/xml,text/html,text/plain
#  server.compression.min-response-size=1024