spring:
  application:
    name: integration-api
  datasource:
    url: jdbc:postgresql://localhost:5432/integration
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
server:
  port: 8080

integration:
  chunk-size: 100