spring:
  application:
    name: integration-api
  datasource:
    url: jdbc:postgresql://localhost:5432/integration
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # todo remove , its redundant
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    locations:
      - classpath:/db/migration
server:
  port: 8080
  shutdown: GRACEFUL
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1

# custom batch config
integration:
  chunk-size: 300
  skip-limit: 100000 # 100k rows
