CREATE TABLE person (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(256) NOT NULL,
  gender VARCHAR(1) DEFAULT NULL,
  birth_date DATE DEFAULT NULL, -- birthdate in documentation, i used same approach as for other dates
  employee_code VARCHAR(8) NOT NULL,
  hire_date DATE NOT NULL,
  termination_date DATE DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT employee_code_unique UNIQUE (employee_code)
);

CREATE TABLE salary_component (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  person_id BIGINT NOT NULL,
  amount DECIMAL(10, 0) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  delete_date DATE DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES person(id)
);

-- add index on foreign key todo retest
--CREATE INDEX salary_component_person_id ON salary_component USING btree (person_id)
